"""
Phase 5 — Documentation generation.
POST /api/v1/docs/generate  →  SRS / ADR / README from graph context.

Works without LLM credits using deterministic graph → markdown.
With credits, enriches with Claude for readable prose.
"""
from enum import StrEnum
from fastapi import APIRouter, Request
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel

from companion.graph.compressor import compress

router = APIRouter()


class DocType(StrEnum):
    SRS     = "srs"
    ADR     = "adr"
    README  = "readme"


class GenerateRequest(BaseModel):
    doc_type: DocType = DocType.SRS
    repo_name: str = "Repository"


@router.post("/generate", response_class=PlainTextResponse)
async def generate_doc(req: GenerateRequest, request: Request) -> str:
    engine = request.app.state.engine

    features     = await engine.neo4j.query("MATCH (f:Feature) RETURN f LIMIT 200")
    relationships = await engine.neo4j.query(
        "MATCH (a)-[r]->(b) RETURN a.id AS source_id, b.id AS target_id, type(r) AS kind LIMIT 500"
    )
    compressed = compress(features, relationships)

    if req.doc_type == DocType.SRS:
        return _generate_srs(req.repo_name, features, compressed)
    if req.doc_type == DocType.README:
        return _generate_readme(req.repo_name, features, compressed)
    return _generate_adr(req.repo_name, compressed)


# ── Deterministic generators ──────────────────────────────────────────────────

def _generate_srs(name: str, features: list, compressed: dict) -> str:
    stats = compressed["stats"]
    by_domain: dict[str, list] = {}
    for f in features:
        by_domain.setdefault(f.get("domain", "unknown"), []).append(f)

    lines = [
        f"# Software Requirements Specification",
        f"## {name}",
        f"",
        f"*Generated by Companion — {stats['total_features']} features, "
        f"{stats['total_relationships']} relationships*",
        f"",
        f"---",
        f"",
        f"## 1. Overview",
        f"",
        f"This document describes the functional capabilities of **{name}** as extracted "
        f"from source code by the Companion intelligence platform.",
        f"",
        f"**Feature summary:** {stats['total_features']} business features across "
        f"{len(by_domain)} domains.",
        f"",
        f"---",
        f"",
        f"## 2. Functional Requirements",
        f"",
    ]

    fr_num = 1
    for domain, domain_features in sorted(by_domain.items()):
        lines.append(f"### 2.{list(by_domain.keys()).index(domain)+1} {domain.replace('-',' ').title()} Domain")
        lines.append("")
        for f in sorted(domain_features, key=lambda x: -x.get("confidence", 0)):
            conf = int(f.get("confidence", 1.0) * 100)
            lines += [
                f"**FR-{fr_num:02d} {f['name']}**  ",
                f"_{f.get('description', '')}_ (confidence: {conf}%)",
                f"",
                f"- Source: `{'`, `'.join(f.get('source_files', [])[:2])}`",
            ]
            if f.get("tags"):
                lines.append(f"- Tags: {', '.join(f['tags'])}")
            lines.append("")
            fr_num += 1

    lines += [
        f"---",
        f"",
        f"## 3. Feature Dependencies",
        f"",
        f"```",
    ]
    for r in compressed.get("relationships", [])[:30]:
        lines.append(f"{r['from']}  →  {r['to']}")
    lines += ["```", ""]

    if compressed.get("semantic_clusters"):
        lines += ["---", "", "## 4. Semantic Clusters", ""]
        for cluster in compressed["semantic_clusters"]:
            lines.append(f"**{cluster.get('cluster_name', 'Cluster')}**")
            lines.append(cluster.get("summary", ""))
            lines.append("")

    return "\n".join(lines)


def _generate_readme(name: str, features: list, compressed: dict) -> str:
    stats = compressed["stats"]
    top = sorted(features, key=lambda f: -f.get("confidence", 0))[:8]
    by_domain: dict[str, int] = {}
    for f in features:
        by_domain[f.get("domain", "unknown")] = by_domain.get(f.get("domain", "unknown"), 0) + 1

    lines = [
        f"# {name}",
        f"",
        f"> Generated by [Companion](https://github.com/amit352/companion) — "
        f"AI-native code intelligence platform",
        f"",
        f"## Overview",
        f"",
        f"{name} contains **{stats['total_features']} business features** across "
        f"**{len(by_domain)} domains**: "
        f"{', '.join(f'{d} ({n})' for d, n in sorted(by_domain.items(), key=lambda x: -x[1]))}.",
        f"",
        f"## Key Features",
        f"",
    ]
    for f in top:
        lines.append(f"- **{f['name']}** — {f.get('description', '')}")
    lines += [
        "",
        "## Domain Breakdown",
        "",
        "| Domain | Features |",
        "|--------|---------|",
    ]
    for d, n in sorted(by_domain.items(), key=lambda x: -x[1]):
        lines.append(f"| {d.title()} | {n} |")
    lines.append("")
    return "\n".join(lines)


def _generate_adr(name: str, compressed: dict) -> str:
    top = compressed["feature_summaries"][:5]
    lines = [
        f"# Architecture Decision Record",
        f"## {name}",
        f"",
        f"**Status:** Accepted  ",
        f"**Date:** *generated by Companion*",
        f"",
        f"## Context",
        f"",
        f"The {name} codebase contains {compressed['stats']['total_features']} "
        f"business features with {compressed['stats']['total_relationships']} dependencies.",
        f"",
        f"## Key Architectural Components",
        f"",
    ]
    for s in top:
        deps = ", ".join(s.get("depends_on", [])[:3])
        lines += [
            f"### {s['name']}",
            f"{s.get('description', '')}",
            *([ f"*Depends on:* {deps}" ] if deps else []),
            "",
        ]
    lines += [
        "## Consequences",
        "",
        "- Features with high in-degree (many dependents) are architectural risk points",
        "- Cross-domain dependencies indicate coupling that should be monitored",
        "",
    ]
    return "\n".join(lines)
